/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Orc.gltf -o src/Componentes/Orc.jsx -r public 
*/
import React, { useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useEffect } from 'react'
import { Clone } from '@react-three/drei'


export default function Orc({hovered,...props}) {
  const group = useRef()
  const { scene, animations, nodes , materials } = useGLTF('/models/Orc.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    console.log("Ações disponíveis:", actions);

      const anim = hovered? 'Weapon':'Idle'
      actions[anim].reset().fadeIn(0.5).play()
  
      return() => actions[anim].fadeOut(0.5)
      
    }, [hovered])
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <skinnedMesh
            name="Orc"
            geometry={nodes.Orc.geometry}
            material={materials.Atlas}
            skeleton={nodes.Orc.skeleton}
          />
          <skinnedMesh
            name="Orc_Weapon"
            geometry={nodes.Orc_Weapon.geometry}
            material={materials.Atlas}
            skeleton={nodes.Orc_Weapon.skeleton}
          />
          <primitive object={nodes.Root} />
        </group>
      </group>
    </group>

  
  )
}

useGLTF.preload('/models/Orc.gltf')
