/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Orc.gltf -o src/Componentes/Orc.jsx -r public 
*/
import React, { useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useEffect } from 'react'
import { Clone } from '@react-three/drei'

export default function Orc(props) {
  const group = useRef()
  const { scene, animations } = useGLTF('/models/Orc.gltf')
  const { actions } = useAnimations(animations, group)


  useEffect(() => {
    console.log(scene)
      actions.Idle.reset().fadeIn(0.5).play()
  
      return() => actions['Idle'].fadeOut(0.5)
      
    }, [actions])
  
  return (
    <group ref={group} {...props} dispose={null}>
      <Clone object={scene}></Clone>
    </group>
  )
}

useGLTF.preload('/models/Orc.gltf')
